addReviewers: true

reviewers:
  - slavastrizh
  - andylovesyou
  - DenisLipin
  - gridnoir
  - OlegMeo
  - MariaGalukha
  - shalaeva-liza
  - TashaRTV
  - sataevru

skipKeywords:
  - wip

numberOfReviewers: 0
