name: PUBLISH

# Ensure npm 11.5.1 or later for trusted publishing
# https://github.com/orgs/community/discussions/173102

on:
    push:
        branches:
            - master

permissions:
    id-token: write
    contents: write

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup node
              uses: actions/setup-node@v6
              with:
                  node-version-file: ".node-version"

            - name: Publish
              run: npm run ci

            - name: Dispatch build icons
              run: curl -X POST -u '${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}' -H 'Accept:\ application/vnd.github.everest-preview+json' -H 'Content-Type:\ application/json' https://api.github.com/repos/core-ds/icons/dispatches --data '{"event_type":"build_application"}'
